FIX: do not return deleted posts in my-reactions
This was causing an error on frontend when reaching for `/u/:username/activity/my-reactions` :

```
TypeError: Cannot read property 'topic' of null
```